# Generated by Django 5.1.3 on 2024-11-18 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0002_provincia_region_tipo_inmueble_comuna_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comuna',
            name='provincia_id',
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='gestion_inmuebles.region'),
        ),
        migrations.DeleteModel(
            name='Provincia',
        ),
    ]
